name: hs-db

services:
  app:
    container_name: app
    image: app
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist-newstyle
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - postgres-network

  database:
    container_name: database
    image: 'postgres:latest'
    ports:
      - 5433:5432
    networks:
      - postgres-network
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./volumes/postgres_data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./volumes/postgres_logs
        target: /var/log/postgresql
    command: >
        -c logging_collector=on
        -c log_directory=/var/log/postgresql
        -c log_filename='postgresql.log'
        -c log_statement=all
        -c log_connections=on
        -c log_disconnections=on
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 15433:80
    depends_on:
      - database
    networks:
      - postgres-network
    volumes:
      - pgadmin:/var/lib/pgadmin/
    environment:
      - PGADMIN_DEFAULT_EMAIL=user1@example.com
      - PGADMIN_DEFAULT_PASSWORD=user1

volumes:
  pgadmin:

networks:
  postgres-network:
    driver: bridge
