name: Documentation

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

permissions:
  contents: write


env:
  GHC_VERSION: "9.10.1"       # Must match setup-haskell's ghc-version
  CABAL_VERSION: "3.14.1.1"  # Must match setup-haskell's cabal-version
  VERSION: "0.0.1"


jobs:
  # INSTALL DEPENDENCIES
  update:
    name: Update
    # container:
      # image: hs-db:latest
      # options: --user root
    runs-on:
      - ubuntu-latest
      - self-hosted


    steps:
    - name: Checkout
      uses: actions/checkout@v4


    # - name: Install Haskell with GHCup
    #   run: |
    #     # Install ghcup (Haskell toolchain installer)
    #     curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
    #     # Add ghcup to PATH
    #     echo "$HOME/.ghcup/bin" >> $GITHUB_PATH
    #     # Install GHC and Cabal
    #     ghcup install ghc ${{ env.GHC_VERSION }}
    #     ghcup set ghc ${{ env.GHC_VERSION }}
    #     ghcup install cabal ${{ env.CABAL_VERSION }}

    - uses: haskell-actions/setup@v2
      with:
        ghc-version: ${{ env.GHC_VERSION }}
        cabal-version: ${{ env.CABAL_VERSION }}

    - name: Cache Cabal store and GHC
      uses: actions/cache@v3
      with:
        path: |
          ~/.cabal/store
          ~/.ghc
          ./dist-newstyle
          ./haddocks
        key: ${{ runner.os }}-ghc-${{ env.GHC_VERSION }}-cabal-${{ env.CABAL_VERSION }}-${{ hashFiles('**/*.cabal') }}-${{ env.VERSION }}
        restore-keys: |
          ${{ runner.os }}-ghc-${{ env.GHC_VERSION }}-cabal-${{ env.CABAL_VERSION }}-

    - name: Update
      run: cabal update

    - name: Build
      run: cabal build all

    - name: Generate Documentation
      run: cabal haddock-project

          # ~/.cabal/store
          # ~/.ghc
          # ./dist-newstyle
          # ./haddocks

    - name: Upload documentation files as artifact
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./haddocks


  # # TEST
  # test:
  #   name: Test
  #   needs: update
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v4

  #   - uses: actions/setup-haskell@v1
  #     with:
  #       ghc-version: ${{ env.GHC_VERSION }}
  #       cabal-version: ${{ env.CABAL_VERSION }}

  #   - name: Update
  #     run: cabal update

  #   - name: Test
  #     run: cabal test all


  deploy:
    name: Deploy
    needs: update
    runs-on: ubuntu-latest

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
