name: Documentation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write


env:
  GHC_VERSION: "9.10.1"       # Must match setup-haskell's ghc-version
  CABAL_VERSION: "3.14.1.1"  # Must match setup-haskell's cabal-version
  CABAL_FILE: "hs-db.cabal"


jobs:
  # INSTALL DEPENDENCIES
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache Cabal store and GHC
      uses: actions/cache@v3
      with:
        path: |
          ~/.cabal/store
          ~/.ghc
        key: ${{ runner.os }}-ghc-${{ env.GHC_VERSION }}-cabal-${{ env.CABAL_VERSION }}-${{ hashFiles(env.CABAL_FILE) }}
        restore-keys: |
          ${{ runner.os }}-ghc-${{ env.GHC_VERSION }}-cabal-${{ env.CABAL_VERSION }}-

    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ env.GHC_VERSION }}
        cabal-version: ${{ env.CABAL_VERSION }}

    - name: Update
      run: cabal update

    - name: Archive update artifacts
      uses: actions/upload-artifact@v4
      with:
        name: update-artifact
        path: |
          ~/.cabal/store
          ~/.ghc
          ./dist-newstyle

  # TEST
  test:
    name: Test
    needs: update
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download a single artifact
      uses: actions/download-artifact@v4
      with:
        name: update-artifact

    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ env.GHC_VERSION }}
        cabal-version: ${{ env.CABAL_VERSION }}

    - name: Test
      run: cabal test all

  # BUILD
  build:
    name: Build
    needs: update
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download a single artifact
      uses: actions/download-artifact@v4
      with:
        name: update-artifact

    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ env.GHC_VERSION }}
        cabal-version: ${{ env.CABAL_VERSION }}

    - name: Build
      run: cabal build all

  # DEPLOY
  generate-docs:
    name: Generate Documentation
    needs: update
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate Documentation
      run: cabal haddock-project

    - name: Upload documentation files as artifact
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./haddocks

  deploy:
    name: Deploy
    needs: generate-docs
    runs-on: ubuntu-latest

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
